#!/bin/bash

echo "Create assets directory"
if ! [ -d assets ] ; then
    mkdir assets
fi
chmod -R g+w assets

echo "Checking for symlink frontend/www/assets"
if ! [ -L frontend/www/assets ]; then
    echo "Creating symlink frontend/www/assets to assets directory"
    SYMASSETS=/assets
    SYMLINK=$(readlink -f frontend/www)
    echo $SYMLINK$SYMASSETS
    TARGET=$(readlink -f assets)
    echo $TARGET
    ln -s $TARGET $SYMLINK$SYMASSETS
fi

echo "Checking for symlink backend/www/assets"
if ! [ -L backend/www/assets ]; then
    echo "Creating symlink backend/www/assets to assets directory"
    SYMASSETS=/assets
    SYMLINK=$(readlink -f backend/www)
    echo $SYMLINK$SYMASSETS
    TARGET=$(readlink -f assets)
    echo $TARGET
    ln -s $TARGET $SYMLINK$SYMASSETS
fi

echo "Set permissions"
chmod -R g+w frontend/protected/runtime
chmod -R g+w frontend/protected/controllers
chmod -R g+w frontend/protected/models
chmod -R g+w frontend/protected/views

chmod -R g+w backend/protected/runtime
chmod -R g+w backend/protected/controllers
chmod -R g+w backend/protected/models
chmod -R g+w backend/protected/views

echo "Install node and grunt dependencies"
npm install

echo "Install vendor components with composer"
composer install
